### ISSUE TITLE
Export failed

### ISSUE THREAD

**Issue by sammilei** [David-Hughes3/CS5990_project#1]
`#Add Libraries to PYTHONPATH`
`!export PYTHONPATH="/content/models/research:/content/models/research/slim"`
`!export PYTHONPATH=/content/models/research/object_detection/:$PYTHONPATH`
didn't successfully set aptend the correct PYTHONPATH but below is another way to do it. I tried and it worked

`import os`
`os.environ['PYTHONPATH'] = ":/content/models/research/slim" #yeeeees works`
`os.environ['PYTHONPATH'] += ":/content/models/research/object_detection" #works`

**Comment by David-Hughes3** [comment]
> `#Add Libraries to PYTHONPATH`
> `!export PYTHONPATH="/content/models/research:/content/models/research/slim"`
> `!export PYTHONPATH=/content/models/research/object_detection/:$PYTHONPATH`
> didn't successfully set aptend the correct PYTHONPATH but below is another way to do it. I tried and it worked

This is because I was using the bash shell/linux commands available to the google colab environment. Anything that starts with the "!" is actually a iPython shell command. So "!" commands might have to be replaced.

**Comment by David-Hughes3** [comment]
My previous comment was wrong, I am not sure why it worked before and not now. I updated the assignment with your suggestion, thank you!


`import os`
`os.environ['PYTHONPATH'] += ":/content/models/research"`
`os.environ['PYTHONPATH'] += ":/content/models/research/slim"`
`os.environ['PYTHONPATH'] += ":/content/models/research/object_detection"`
